# Generated by Django 4.2.1 on 2023-05-26 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(35), django.core.validators.MinValueValidator(18)])),
                ('genre', models.CharField(choices=[('Masculin', 'Homme'), ('Féminin', 'Femme')], max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
